#!/bin/bash 
#
# Author Rigoberto Leander Salgado Reyes <rlsalgado2006@gmail.com>
#
# Copyright 2016 by Rigoberto Leander Salgado Reyes.
#
# This program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http:www.gnu.org/licenses/agpl-3.0.txt) for more details.

E_NOFILE=86

function main {
	if [ $# -lt 1 ]
	then
		usage
	fi

	name=`echo "$1" | awk '{sub(/\.\w+/, ""); print}'`

	case "$2" in
		compile)
			echo '<=== Iniciando compilación ===>'
			echo 'Creado DVI'
			action "$name.tex" 'latex -interaction=nonstopmode'
			echo 'Creado PS'
			action "$name.dvi" 'dvips'
			echo 'Creado PDF'
			action "$name.ps" 'ps2pdf'
			echo '<=== Finalizando compilación ===>'
		;;
		
		clean)
			echo '<=== Iniciando limpieza ===>'
			rm -f *.pdf *.ps *.dvi *.log *.aux
			echo '<=== Finalizando limpieza ===>'
		;;
		
		*)
			usage
		;;
	esac
}

function action {
	if [ -f "$1" ]          # Comprueba la existencia del fichero.
	then
		$2 $1 >& /dev/null   # Ejecuta la acción.
	else
		echo "El fichero \"$1\" no existe."
		exit $E_NOFILE
	fi
}

function usage {
	name=`echo "$0" | awk '{sub(/\.\//, ""); print}'`
	echo "Modo de uso: <nombre>.$name {compile|clean}"
	exit 1
}

main "$@"
